title: Shibo Simon Jia
logo: /Personal/Portrait.jpg
description: Mechanical Designer / Structural Optimization

project_info:
  - title: Gearbox Optimization
    url: /Portfolio/Altair_Intern_Samples/Gearbox_Sample/Altair_1.html
  - title: Topology Optimization of Gear
    url: /Portfolio/Altair_Intern_Samples/Gearbox_Sample/Gear_Topo_Sample.html
  - title: Shape Optimization of Shaft
    url: /Portfolio/Altair_Intern_Samples/Gearbox_Sample/Shaft_Shape_Sample.html

theme: jekyll-theme-minimal

