title: Shibo Simon Jia
logo: /Personal/Portrait.jpg
description: >
  <strong>Mechanical Designer / Structural Optimization</strong><br><br>
  Altair Intern Work Samples:<br>
  <a href="/Portfolio/Altair_Intern_Samples/Gearbox_Sample/Altair_1.html">Gearbox Optimization</a><br>

  Thermal Design:<br><br>

  <span style="font-size:16px; color:blue">[Back to the Home Page](https://shibojia98.github.io/Portfolio/)</span><br><br>
theme: jekyll-theme-minimal

