title: Shibo Simon Jia
logo: /Personal/Portrait.jpg
description: Mechanical Designer/ Structural Optimization<br><br><br>
project_info: "Altair Intern Work Sample: [Gearbox Optimization](https://shibojia98.github.io/Portfolio/Altair_Intern_Samples/Gearbox_Sample/Altair_1.html)"
project_info: "Altair Intern Work Sample: [Topology Optimization of Gear](https://shibojia98.github.io/Portfolio/Altair_Intern_Samples/Gearbox_Sample/Gear_Topo_Sample.html)"
project_info: "Altair Intern Work Sample: [Shape Optimization of Shaft](https://shibojia98.github.io/Portfolio/Altair_Intern_Samples/Gearbox_Sample/Shaft_Shape_Sample.html)"

theme: jekyll-theme-minimal

