title: Shibo Simon Jia
logo: /Personal/Portrait.jpg
description: >
  <strong>Mechanical Designer / Structural Optimization</strong><br><br>

  Altair Intern Work Samples:<br>
  <a href="/Portfolio/Altair_Intern_Samples/Gearbox_Sample/Altair_1.html">Gearbox Optimization</a><br>


  Thermal Design:<br>
  <a href="/Portfolio/Thermal_Design/Thermal_Design.md">Thermal-Mechanical Design Case Study</a><br><br>
  <a href="https://shibojia98.github.io/Portfolio/">*Back to the Home Page</a><br>

theme: jekyll-theme-minimal
